version: "3.0"
services:
  db:
    container_name: "education_db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5434:5432"
    networks:
      - custom
  fastapi_education_service:
    container_name: fastapi_education_service
    image: fastapi_education_service
    environment:
      REAL_DATABASE_URL: "postgresql+asyncpg://postgres:postgres@db:5432/postgres"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    networks:
      - custom
networks:
  custom:
    driver: bridge
